name: Arduino CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
        arduino-cli core update-index
        arduino-cli core update-index --additional-urls https://dl.espressif.com/dl/package_esp32_index.json
        arduino-cli core install esp32:esp32 --additional-urls https://dl.espressif.com/dl/package_esp32_index.json

    - name: Compile sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:nodemcu-32s ${{ github.workspace }}/examples/dshot300
      env:
        ARDUINO_LIBRARY_PATH: ${{ github.workspace }}/libraries
        ARDUINO_DATA_PATH: ${{ github.workspace }}/arduino-data
